version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8005:8000

  celery:
    build: .
    command: celery -A polls_django_app worker -B -l INFO
    environment:
        - DJANGO_SETTINGS_MODULE=polls_django_app.settings
    volumes:
      - .:/app
    depends_on:
      - web

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
